"""📝 Content — editorial calendar + content tooling."""
from __future__ import annotations

import datetime as dt

import pandas as pd
import streamlit as st

from app.db import (
    add_content_item,
    delete_content_item,
    init_db,
    list_content,
    update_content_status,
)
from app.ui_helpers import (
    ACCENT, BG_CARD, BORDER, TEXT_MUTED, TEXT_PRIMARY,
    empty_state_card, logo_html,
)

st.markdown(
    f"""
    <div style="background:linear-gradient(135deg,#0d1117 0%,#161B22 100%);
                border:1px solid {BORDER};border-radius:14px;
                padding:20px 24px;margin-bottom:24px;">
      <div style="display:flex;align-items:center;gap:14px;margin-bottom:6px;">
        {logo_html(height=36)}
        <div style="font-size:0.78rem;color:{ACCENT};letter-spacing:0.14em;
                    text-transform:uppercase;font-weight:600;">Editorial</div>
      </div>
      <h1 style="margin:0 0 8px;font-size:1.7rem;color:{TEXT_PRIMARY};">
        📝 Content Calendar
      </h1>
      <div style="color:{TEXT_MUTED};font-size:0.92rem;line-height:1.55;">
        Editorial pipeline from idea → published. Maya can add items via tool
        (<code>content_calendar_add</code>) and you can manage status here.
      </div>
    </div>
    """,
    unsafe_allow_html=True,
)

init_db()

with st.expander("➕ Add a content item", expanded=False):
    col1, col2 = st.columns(2)
    with col1:
        title = st.text_input("Title", placeholder="e.g. Beginner's guide to AI options trading")
        target_kw = st.text_input("Target keyword", placeholder="AI options trading")
        target_url = st.text_input("Target URL (planned)",
                                    placeholder="https://stoptions.ai/guides/ai-options-trading")
        intent = st.selectbox("Intent",
                              ["informational", "commercial", "navigational", "transactional"])
    with col2:
        ctype = st.selectbox("Content type",
                             ["blog", "landing", "guide", "tool", "comparison", "listicle"])
        owner = st.text_input("Owner", placeholder="Maya / writer name")
        due = st.date_input("Due date", value=None)
        word_count = st.number_input("Word-count target", min_value=0, value=1500, step=100)
    outline = st.text_area("Outline / brief", height=120,
                            placeholder="H2 sections, key points to cover, FAQ block, schema needed…")
    if st.button("Add to calendar", type="primary", disabled=not title):
        add_content_item(
            title=title, target_keyword=target_kw, intent=intent,
            content_type=ctype, owner=owner,
            due_date=due.isoformat() if due else "",
            target_url=target_url, word_count=int(word_count),
            outline=outline,
        )
        st.success("Added.")
        st.rerun()

st.markdown("---")

STAGES = ["idea", "brief", "drafting", "review", "scheduled", "published", "archived"]
tabs = st.tabs([f"💡 Idea", "📋 Brief", "✍️ Drafting", "🔎 Review",
                "📅 Scheduled", "✅ Published", "📦 Archived"])

for tab, stage in zip(tabs, STAGES):
    with tab:
        items = list_content(status=stage)
        if not items:
            _hint = {
                "idea": "Topic ideas live here — either added by you manually or generated by Maya via topic_cluster_planner.",
                "brief": "Items with a finished brief ready for a writer. Should include outline, target keyword, intent, and word-count target.",
                "drafting": "Currently being written. If a piece sits here too long, surface it on Linz's status report.",
                "review": "Drafts ready for SEO/editorial review before publish.",
                "scheduled": "Approved + queued for publication in the CMS.",
                "published": "Live. Cash will measure rank + traffic uplift at +14d / +28d.",
                "archived": "Retired posts — kept for reference but excluded from active reporting.",
            }.get(stage, "")
            st.markdown(
                empty_state_card(
                    icon={"idea":"💡","brief":"📋","drafting":"✍️","review":"🔎","scheduled":"📅","published":"✅","archived":"📦"}[stage],
                    title=f"Nothing in {stage}",
                    body=_hint,
                ),
                unsafe_allow_html=True,
            )
            continue
        for item in items:
            with st.container(border=True):
                col1, col2 = st.columns([4, 1])
                with col1:
                    meta = []
                    if item.get("target_keyword"):
                        meta.append(f"🎯 {item['target_keyword']}")
                    if item.get("content_type"):
                        meta.append(item["content_type"])
                    if item.get("owner"):
                        meta.append(f"👤 {item['owner']}")
                    if item.get("due_date"):
                        meta.append(f"📅 due {item['due_date']}")
                    if item.get("word_count"):
                        meta.append(f"~{item['word_count']} words")
                    meta_str = " · ".join(meta)
                    st.markdown(f"**#{item['id']} · {item['title']}**")
                    if meta_str:
                        st.caption(meta_str)
                    if item.get("target_url"):
                        st.caption(f"🔗 {item['target_url']}")
                    if item.get("outline"):
                        with st.expander("Outline / brief"):
                            st.markdown(item["outline"])
                    if item.get("status_note"):
                        st.caption(f"_Note: {item['status_note']}_")
                with col2:
                    next_status = st.selectbox(
                        "Move to", [""] + STAGES,
                        key=f"cmv_{item['id']}_{stage}",
                        label_visibility="collapsed",
                    )
                    if next_status and next_status != item["status"]:
                        update_content_status(item["id"], next_status)
                        st.rerun()
                    if st.button("🗑", key=f"cdel_{item['id']}_{stage}"):
                        delete_content_item(item["id"])
                        st.rerun()
